# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c6989f5678208c9c59c707f1b4cd4a0bbd2c5b7b9fdfdbc7c5f700e679b6b2618916afc463eea3d80abb97314448188a9355833d70e8f7e27605832fade44e3

test:
  secret_key_base: 51f06a0eb2a332ff59616428a69ebe4224b59e60f1780acbcca1fda963c76d242940644fbd40f0968e364cb383745810e2396e93c4f600b041fedfd657835d5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
